default: &default
  adapter: postgresql
  user: postgres
  password: password
  pool: 5
  encoding: unicode

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  adapter: postgresql
  database: myapp_production
  pool: 5
  encoding: unicode